// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  Helpers: [{ type: "autogenerated", dirName: "scripts" }],
  FullStack: [{ type: "autogenerated", dirName: "FullStack" }],
  Applications: [{ type: "autogenerated", dirName: "apps" }],
};

module.exports = sidebars;
